# Generated by Django 4.2.28 on 2026-02-20 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Mode d'acquisition",
                'verbose_name_plural': "Modes d'acquisition",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('valide', 'Validé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('total_items', models.IntegerField(default=0, verbose_name='Total articles')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valeur totale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code article')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='N° de série')),
                ('condition', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('usage', 'Usage normal'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état')], default='neuf', max_length=20, verbose_name='État')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('min_stock', models.IntegerField(default=1, verbose_name='Stock minimum')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Image')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('affecte', 'Affecté'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('reforme', 'Réformé')], default='disponible', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='N° TVA')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('donor', models.CharField(blank=True, max_length=200, verbose_name='Donateur')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='N° facture')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='N° bon')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date mouvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('acquisition_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.acquisitionmode', verbose_name="Mode d'acquisition")),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.employee', verbose_name='Bénéficiaire')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Article')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_quantity', models.IntegerField(verbose_name='Quantité théorique')),
                ('actual_quantity', models.IntegerField(verbose_name='Quantité réelle')),
                ('difference', models.IntegerField(default=0, editable=False, verbose_name='Différence')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('theoretical_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('value_difference', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['code'], name='inventory_i_code_0aa0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='inventory_i_status_25f563_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='inventory_i_categor_dcc1fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'item')},
        ),
    ]
