# Generated by Django 4.2.28 on 2026-02-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='beneficiary',
        ),
    ]
